
title: Цитрониум
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/citronium-landing" # the subpath of your site, e.g. /blog
url: "https://citronium.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima

# autoprefixer:
#   only_production: true

plugins:
  - jekyll-feed
  - jekyll-autoprefixer