title: Citronium | Разработка веб и мобильных приложений, высоконагруженных систем | Студия Citronium
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://citronium.ru" # the base hostname & protocol for your site, e.g. http://example.com
lang: ru

# Build settings
theme: minima

# autoprefixer:
#   only_production: true

plugins:
    - jekyll-feed
    - jekyll-autoprefixer
