version: '3'
services:  
  app:
    image: registry.citronium.com/citronium-landing:${APP_VERSION:-latest}    
    container_name: citronium-landing
    volumes:
      - citronium_landing:/var/www/html
    #restart: always
    labels:
      - traefik.backend=citronium-landing
      - traefik.frontend.rule=Host:citronium-landing.psrv5.citronium.com
      - traefik.port=80
      - traefik.docker.network=traefik_proxy
    networks:      
      - traefik
networks:
  traefik:
    external:
      name: traefik_proxy
volumes:
  citronium_landing:
